[package]
name = "obmc-cloud-client"
version = "0.3.0"
authors = ["Matthew Burns <matt@packet.com>"]
edition = "2018"

[dependencies]
rustbus = "0.6.0"

[dependencies.reqwest]
version = "0.10"
default-features = false
features = ["json", "rustls-tls", "blocking"]
